Sirindar/Models/AsignacionBloquesViewModels.cs
using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;

namespace Sirindar.Models
{
    public class CreateAsignacionBloquesViewModel
    {
        [Required]
        [Remote("IsDeportista", "Validations", ErrorMessage = "El deportista no existe")]
        public virtual int DeportistaId { get; set; }

        [Required]
        [Remote("IsDeporte", "Validations", ErrorMessage = "El deporte no existe")]
        public virtual int DeporteId { get; set; }

        [Required]
        [Remote("IsBloque", "Validations", ErrorMessage = "El deporte no existe")]
        public virtual int BloqueId { get; set; }
    }

    public class UpdateAsignacionBloquesViewModel
    {
        public virtual int AsignacionBloqueId { get; set; }

        [Required]
        [Remote("IsDeportista", "Validations", ErrorMessage = "El deportista no existe")]
        public virtual int DeportistaId { get; set; }

        [Required]
        [Remote("IsDeporte", "Validations", ErrorMessage = "El deporte no existe")]
        public virtual int DeporteId { get; set; }

        [Required]
        [Remote("IsBloque", "Validations", ErrorMessage = "El deporte no existe")]
        public virtual int BloqueId { get; set; }

    }
}

Sirindar/Controllers/AsignacionBloquesController.cs
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Newtonsoft.Json;
using Sirindar.Core.UnitOfWork;
using Sirindar.Core;
using System.Net;

namespace Sirindar.Controllers
{
    public class AsignacionBloquesController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;

        public AsignacionBloquesController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        // GET: /AsignacionBloques
        public ActionResult Index()
        {
            ViewBag.json =
                new HtmlString(JsonConvert.SerializeObject(GridAsignaciones().Deportistas,
                    new JsonSerializerSettings { ReferenceLoopHandling = ReferenceLoopHandling.Ignore }));
            return View();
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(AsignacionBloque asignacionBloque)
        {
            _unitOfWork.AsignacionesBloques.Add(new AsignacionBloque
            {
                DeportistaId = asignacionBloque.DeportistaId,
                DeporteId = asignacionBloque.DeporteId,
                BloqueId = asignacionBloque.BloqueId
            });
            _unitOfWork.Complete();
            return RedirectToAction("Index");
        }

        public JsonResult GetDeportistas(int draw, int start, int length)
        {
            var value = HttpContext.Request.Params["search[value]"];
            var recordsTotal = _unitOfWork.Deportistas.Count();
            var deportistas = _unitOfWork.Deportistas
                .GetAllByExpression(value)
                .Select(d => new
                {
                    DT_RowId = "row_" + d.DeportistaId,
                    DT_RowData = new
                    {
                        pkey = d.DeportistaId
                    },
                    d.Matricula,
                    d.Nombre,
                    d.Apellidos
                }).ToList();
            var data = deportistas.Skip(start).Take(length);
            return Json(new
            {
                draw,
                recordsTotal,
                recordsFiltered = deportistas.Count,
                data
            }, JsonRequestBehavior.AllowGet);
        }

        public ActionResult AddBloque(string matricula)
        {
            ViewBag.Deportista = _unitOfWork.Deportistas.GetByMatricula(matricula);
            return PartialView();
        }

        public JsonResult GetBloques()
        {
            return Json(_unitOfWork.Bloques.GetAll(), JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetDeportes(string matricula)
        {
            return Json(_unitOfWork.Deportistas.GetDeportes(matricula), JsonRequestBehavior.AllowGet);
        }

        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var model = _unitOfWork.AsignacionesBloques.Get(id.Value);
            if (model == null)
            {
                return HttpNotFound();
            }
            return PartialView(model);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            var asignacionBloque = _unitOfWork.AsignacionesBloques.Get(id);
            _unitOfWork.AsignacionesBloques.Remove(asignacionBloque);
            _unitOfWork.Complete();
            return RedirectToAction("Index");
        }

        public TableAsignacionBloques GridAsignaciones()
        {
            var groupDeportistas = _unitOfWork.AsignacionesBloques.GetAsignacionBloquesByMatriucla();

            var tableAsignaciones = new TableAsignacionBloques { Deportistas = new List<RowDeportista>() };

            foreach (var deportista in groupDeportistas)
            {
                var key = deportista.Key;
                var rowDeportista = deportista
                    .Where(x => x.Deportista.Matricula == key)
                    .Select(x => new RowDeportista
                    {
                        Matricula = x.Deportista.Matricula,
                        Nombre = x.Deportista.Nombre,
                        DeportistaId = x.DeportistaId
                    }).First();

                rowDeportista.Deportes = new List<RowDeporte>();

                var groupDeporte = deportista.Where(x => x.Deportista.Matricula == key).GroupBy(x => x.DeporteId).ToList();

                var listIds = new List<int>();
                foreach (var deporte in groupDeporte)
                {
                    var key2 = deporte.Key;
                    var rowDeporte = deporte
                        .Where(x => x.DeporteId == key2)
                        .Select(x => new RowDeporte
                        {
                            DeporteId = x.DeporteId,
                            Nombre = x.Deporte.Nombre
                        }).First();

                    var listRowBloque = deporte
                        .Where(dd => dd.DeporteId == key2)
                        .Select(dd =>
                        {
                            return new RowBloque
                            {
                                Nombre = dd.Bloque.Nombre,
                                // ReSharper disable once PossibleInvalidOperationException
                                BloqueId = dd.BloqueId.Value,
                                AsignacionBloqueId = dd.AsignacionBloqueId
                            };
                        }).ToList();

                    rowDeporte.Bloques = listRowBloque;
                    rowDeporte.RowSpan = listRowBloque.Select(lrb => lrb.AsignacionBloqueId).ToArray();
                    listIds.AddRange(listRowBloque.Select(lrb => lrb.AsignacionBloqueId).ToArray());
                    rowDeportista.Deportes.Add(rowDeporte);
                }
                rowDeportista.RowSpan = listIds.ToArray();
                tableAsignaciones.Deportistas.Add(rowDeportista);
            }

            return tableAsignaciones;

        }

        //public class DataTablesParams
        //{
        //    public int draw;
        //    public int start;
        //    public int length;
        //    public search search;
        //    public order[] order;
        //    public column[] columns;
        //}

        //public class order
        //{
        //    public int column;
        //    public string dir;
        //}

        //public class column
        //{
        //    public string data;
        //    public string name;
        //    public bool searchable;
        //    public bool orderable;
        //    public search search;
        //}

        //public class search
        //{
        //    public string value;
        //    public bool regex;
        //}

        public class TableAsignacionBloques
        {
            public List<RowDeportista> Deportistas { get; set; }
        }

        public class RowDeportista
        {
            public int[] RowSpan { get; set; }
            public int DeportistaId { get; set; }
            public string Matricula { get; set; }
            public string Nombre { get; set; }
            public List<RowDeporte> Deportes { get; set; }
        }

        public class RowDeporte
        {
            public int[] RowSpan { get; set; }
            public int DeporteId { get; set; }
            public string Nombre { get; set; }
            public List<RowBloque> Bloques { get; set; }
        }

        public class RowBloque
        {
            public int BloqueId { get; set; }
            public int AsignacionBloqueId { get; set; }
            public string Nombre { get; set; }
        }
    }
}

Sirindar/Controllers/ValidationsController.cs
using System.Web.Mvc;
using System.Web.UI;
using Sirindar.Core.UnitOfWork;


namespace Sirindar.Controllers
{
    public class ValidationsController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;

        public ValidationsController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        [OutputCache(Location = OutputCacheLocation.None, NoStore = true)]
        public JsonResult MatriculaExist(string matricula)
        {
            return Json(!_unitOfWork.Deportistas.IsMatricula(matricula), JsonRequestBehavior.AllowGet);
        }

        public JsonResult IsDeporte(int deporteid)
        {
            return Json(!_unitOfWork.Deportes.IsDeporte(deporteid), JsonRequestBehavior.AllowGet);
        }

        public JsonResult IsDependencia(int dependenciaid)
        {
            return Json(!_unitOfWork.Dependencias.IsDependencia(dependenciaid), JsonRequestBehavior.AllowGet);
        }

        public JsonResult IsDeportista(int deportistaid)
        {
            return Json(!_unitOfWork.Deportistas.IsDeportista(deportistaid), JsonRequestBehavior.AllowGet);
        }

        public JsonResult IsBloque(int bloqueid)
        {
            return Json(!_unitOfWork.Bloques.IsBloque(bloqueid), JsonRequestBehavior.AllowGet);
        }

        public JsonResult IsAsignacionBloques(int deportistaId, int deporteId, int bloqueId)
        {
            return Json(!_unitOfWork.AsignacionesBloques.IsAsigancionGrupos(deportistaId, deporteId, bloqueId), JsonRequestBehavior.AllowGet);
        }
    }
}

Sirindar/Views/AsignacionBloques/AddBloque.cshtml
@using (Html.BeginForm("Create", "AsignacionBloques", FormMethod.Post, new { id = "create-form" }))
{
    @Html.AntiForgeryToken()
    @Html.Hidden("DeportistaId", 0);
    @Html.Hidden("DeporteId", 0);
    @Html.Hidden("BloqueId", 0);
    <div class="modal-header">
        <h4>Agregar bloque</h4>
    </div>
    <div class="modal-body">
        <div class="row">
            <div class="col-md-12">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <table class="table" id="tbl-deportes">
                            <thead>
                                <tr>
                                    <th>Deporte</th>
                                </tr>
                            </thead>
                            <tbody></tbody>
                        </table>
                    </div>
                </div>
            </div>
            <div class="col-md-12">
                <div class="label label-danger hidden" id="label-required-deporte">Debes seleccionar un deporte</div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <div class="table-responsive">
                    <div class="panel panel-default collapse">
                        <div class="panel-heading">
                            Bloques
                        </div>
                        <div class="panel-body">
                            <div class="dataTable_wrapper">
                                <div id="dataTables-example_wrapper1" class="dataTables_wrapper form-inline dt-bootstrap no-footer">
                                    <div class="row">
                                        <div class="col-md-12">
                                            <table id="tbl-bloques" class="table table-striped table-bordered table-hover " cellspacing="0" width="100%">
                                                <thead>
                                                    <tr>
                                                        <th>Nombre</th>
                                                        <th>Kilocalorias</th>
                                                    </tr>
                                                </thead>
                                            </table>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-12">
                <div class="label label-danger hidden" id="label-required-bloque">Debes seleccionar un bloque</div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12" id="div-lbl-breadcrums">
                <div class='fa fa-arrow-circle-right'></div> <div class="label label-success">@ViewBag.Deportista.Matricula @ViewBag.Deportista.ToString()</div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <hr />
                <div class="alert alert-danger hidden" id="alert-isAsignacionBloque"></div>
            </div>
        </div>
    </div>
    <div class="modal-footer">
        <div class="row">
            <div class="col-md-12">
                <input type="submit" value="Ok" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<script>

    var asignacionBloques = {
        DeportistaId : 0,
        DeporteId : 0,
        BloqueId : 0
    };

    asignacionBloques.DeportistaId = @ViewBag.Deportista.DeportistaId;

    $.get("@Url.Action("GetDeportes","AsignacionBloques")", { matricula : @ViewBag.Deportista.Matricula }).success(function (json) {
        $.each(json, function (key, value) {
            $("#tbl-deportes tbody").first().append(
                "<tr>" +
                "<td><a href='#' onclick='addDeporte("+ value.DeporteId +",\""+ value.Nombre +"\")'>" + value.Nombre + "</a></td>"
                + "</tr>");
        });
    });

    function addDeporte(deporteId, nombre){
        $("#label-required-deporte").addClass("hidden");
        asignacionBloques.DeporteId = deporteId;
        $(".remove").remove();
        $("#div-lbl-breadcrums").append(" <div class='fa fa-arrow-circle-right remove'></div> <div class='label label-success remove'>"+ nombre +"</div>");
        $(".collapse").collapse();
    }

    function addBloque(bloqueId, nombre){
        $("#label-required-bloque").addClass("hidden");
        asignacionBloques.BloqueId = bloqueId;
        $(".remove-l").remove();
        $("#div-lbl-breadcrums").append(" <div class='fa fa-arrow-circle-right remove-l'></div> <div class='label label-success remove-l'>"+ nombre +"</div>");
    }

    $('#tbl-bloques').dataTable({
        "ajax":
            {
                "url" : "@Url.Action("GetBloques","AsignacionBloques")",
                "dataSrc" : function(json){
                    return json;
                }
            },
        "columns": [
            {
                "data": "Nombre",
                "render": function (data, type, row, meta) {
                    return '<a href="#" onclick="addBloque('+ row.BloqueId +',\''+ row.Nombre +'\')">' + data + '</a>';
                }
            },
            { "data": "KilocaloriasTotales" },
        ]
    });

    //$("#create-form").submit(function(){

    //    return true;
    //});

    $('#create-form').submit(function(e) {
        // this code prevents form from actually being submitted
        e.preventDefault();
        e.returnValue = false;

        $("input[name='DeportistaId']").attr('value', asignacionBloques.DeportistaId);
        $("input[name='DeporteId']").attr('value', asignacionBloques.DeporteId);
        $("input[name='BloqueId']").attr('value', asignacionBloques.BloqueId);

        if($("input[name='DeporteId']").val() == 0) {
            $("#label-required-deporte").removeClass("hidden");
            return;
        }

        if($("input[name='BloqueId']").val() == 0){
            $("#label-required-bloque").removeClass("hidden");
            return;
        }

        var $form = $(this);

        // this is the important part. you want to submit
        // the form but only after the ajax call is completed
        $.ajax({
            type: 'get',
            url: '@Url.Action("IsAsignacionBloques", "Validations")',
            data: asignacionBloques,
            context: $form, // context will be "this" in your handlers
            success: function(ok) {
                if(ok){
                    this.off('submit');
                    this.submit();
                }
                else{
                    $("#alert-isAsignacionBloque").removeClass("hidden");
                    $("#alert-isAsignacionBloque").text("El deportista ya tiene esta asignacion");
                }
            },
            error: function() {
                $("#alert-isAsignacionBloque").removeClass("hidden");
                $("#alert-isAsignacionBloque").text("A ocurrido un error");
            }
        });
    });

</script>

Sirindar/Views/AsignacionBloques/Create.cshtml
@*<link href="~/Content/jquery.dataTables.min.css" rel="stylesheet" />*@
<link href="~/Content/dataTables.bootstrap.css" rel="stylesheet" />
<div class="row">
    <div class="col-md-12">
        <h2 class="page-header">Asignacion de bloque</h2>
    </div>
</div>
<div class="row">
    <div class="table-responsive">
        <div class="col-md-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    Busqueda de deportistas
                </div>
                <div class="panel-body">
                    <div class="dataTable_wrapper">
                        <div id="dataTables-example_wrapper" class="dataTables_wrapper form-inline dt-bootstrap no-footer">
                            <div class="row">
                                <div class="col-md-12">
                                    <table id="tbl-deportistas" class="table table-striped table-bordered table-hover " cellspacing="0" width="100%">
                                        <thead>
                                            <tr>
                                                <th>Matricula</th>
                                                <th>Nombre</th>
                                                <th>Apellidos</th>
                                            </tr>
                                        </thead>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@section Scripts{
    <script src="~/Scripts/jquery.dataTables.min.js"></script>
    <script src="~/Scripts/dataTables.bootstrap.js"></script>
    <script>
        var tbl_deportistas = $('#tbl-deportistas').dataTable({
            processing: true,
            serverSide: true,
            ajax :
                {
                    //"data": function (data) {
                    //    data = JSON.stringify(data);
                    //},
                    "url" : "@Url.Action("GetDeportistas", "AsignacionBloques")",
                    "type": 'POST'
                },
            columns : [
                {
                    "data": "Matricula",
                    "orderable": false,
                    "searchable": false,
                    "render": function (data) {
                        return '<a href="#" onclick="displayModal(' + data + ')">' + data + '</a>';
                    }
                },
                { "data": "Nombre" },
                { "data": "Apellidos" }
            ]
        });

        function displayModal(matricula) {

            $.get("@Url.Action("AddBloque", "AsignacionBloques")",{ matricula }).success(function (html) {
                $("#idModal .modal-content").replaceWith('<div class="modal-content">' + html + '</div>');
                $("#idModal").modal('show');
            });
        }

    </script>
}

Sirindar/Views/AsignacionBloques/Delete.cshtml
@model Sirindar.Core.AsignacionBloque

<div class="modal-header">
    <div class="row">
        <div class="col-md-12">
            <h4>
                Quieres borrar esta asignacion?
            </h4>
        </div>
    </div>
</div>
<div class="modal-body">
    <div class="row">
        <div class="col-md-12">
            <dl class="dl-horizontal">
                <dt>
                    Deportista
                </dt>

                <dd>
                    @Model.Deportista.ToString()
                </dd>

                <dt>
                    Deporte
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Deporte.Nombre)
                </dd>

                <dt>
                    Bloque
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Bloque.Nombre)
                </dd>
            </dl>
        </div>       
    </div>
</div>
<div class="modal-footer">
    <div class="row">
        <div class="col-md-12">
            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()

                <div class="form-actions no-color">
                    <input type="submit" value="Delete" class="btn btn-default" /> |
                    @Html.ActionLink("Regresar", "Index")
                </div>
            }
        </div>
    </div>
</div>

Sirindar/Views/AsignacionBloques/Index.cshtml
@{
    ViewBag.Title = "Inicio";
    var json = (HtmlString)ViewBag.json;
}
<div class="row">
    <div class="col-md-12">
        <h2 class="page-header">Asignación de bloque</h2>
    </div>
</div>
<div class="row" ng-app="listApp" ng-controller="listController">
    <div class="col-md-12">
        <div>
            <div class="alert alert-info alert-dismissible" role="alert" ng-hide="items.length != 0">
                <strong>{{ message }}</strong>
            </div>
        </div>
        <div class="table-responsive">
            <div>
                <div class="col-md-6">
                    <div class="input-group">
                        <span class="input-group-addon" id="basic-addon1">
                            <span class="glyphicon glyphicon-search" aria-hidden="true">
                            </span>
                        </span>
                        <input type="text" class="form-control" placeholder="Buscar..." aria-describedby="basic-addon1" ng-model="strCadena" ng-keyup="serch(strCadena)">
                    </div>
                </div>
                <div class="col-md-offset-3 col-md-3">
                    @Html.ActionLink("Nueva Asignacion","Create")
                </div>
                <div class="col-md-12">
                    <table class="table table-condensed">
                        <thead>
                            <tr>
                                <th class="row">#</th>
                                <th>Matricula</th>
                                <th>Nombre</th>
                                <th>Deporte</th>
                                <th>Bloque</th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr ng-repeat-start="(k,p) in tempItems" ng-if="false"></tr>
                            <tr ng-repeat-start="c in p.Deportes" ng-if="false"></tr>
                            <tr ng-repeat="s in c.Bloques">
                                <th ng-if="$parent.$first && $first" rowspan="{{p.RowSpan.length}}">
                                    {{k+1}}
                                </th>
                                <td ng-if="$parent.$first && $first" rowspan="{{p.RowSpan.length}}">
                                    {{p.Matricula}}
                                </td>
                                <td ng-if="$parent.$first && $first" rowspan="{{p.RowSpan.length}}">
                                    {{p.Nombre}}
                                </td>                             
                                <td ng-if="$first" rowspan="{{c.RowSpan.length}}">{{c.Nombre}}</td>
                                <td>{{s.Nombre}}</td>
                                <td ng-if="s.Nombre == 'Sin bloque' || s.BloqueId == 0" >
                                    <a ng-href="@Url.Action("Edit")/{{s.AsignacionBloqueId}}"><span class="glyphicon glyphicon-plus"></span></a>&ensp;
                                </td>                               
                                <td ng-if="s.Nombre != 'Sin bloque' && s.BloqueId != 0">
                                    <a href="#" ng-click="deleteConfirm('@Url.Action("Delete")', s.AsignacionBloqueId)"><span class="glyphicon glyphicon-remove"></span></a>&ensp;
                                </td>
                            </tr>
                            <tr ng-repeat-end ng-if="false"></tr>
                            <tr ng-repeat-end ng-if="false"></tr>
                        </tbody>
                    </table>
                </div>
                <div class="col-md-12" ng-hide="isHide">
                    <ul class="pagination pull-right">
                        <li ng-click="changePage(pages[0])">
                            <a href="#">
                                <span>Primera</span>
                            </a>
                        </li>
                        <li ng-click="changePage(currentPage - 1)">
                            <a href="#">
                                <span><<</span>
                            </a>
                        </li>
                        <li ng-repeat="x in tempPages" ng-click="changePage(x)" ng-class="{active: x == currentPage}">
                            <a href="#">
                                <span>{{x}}</span>
                            </a>
                        </li>
                        <li ng-click="changePage(currentPage + 1)">
                            <a href="#">
                                <span>>></span>
                            </a>
                        </li>
                        <li ng-click="changePage(pages[pages.length - 1])">
                            <a href="#">
                                <span>Ultima</span>
                            </a>
                        </li>
                        <li ng-click="sp(n = n + count, count)" ng-hide="notMore || (currentPage != tempPages[tempPages.length - 1])">
                            <a href="#">
                                <span>Load</span>
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>
@section scripts
{
    <script>      
        jsPageing('@json', "@Url.Action("GetItemsJson")", 10, 9);
    </script>
}