Sirindar/Controllers/BloquesController.cs
using System.Net;
using System.Web;
using System.Web.Mvc;
using Newtonsoft.Json;
using Sirindar.Core;
using Sirindar.Core.UnitOfWork;

namespace Sirindar.Controllers
{
    [Authorize(Roles = "Admin")]
    public class BloquesController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;

        public BloquesController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }


        public ActionResult Index()
        {
            ViewBag.json = new HtmlString(JsonConvert.SerializeObject(_unitOfWork.Bloques.GetAll(), new JsonSerializerSettings { ReferenceLoopHandling = ReferenceLoopHandling.Ignore }));
            return View();
        }

        // GET: /Bloques/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: /Bloques/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "BloqueId,Nombre,KilocaloriasTotales")] Bloque bloque)
        {
            if (ModelState.IsValid)
            {
                _unitOfWork.Bloques.Add(bloque);
                _unitOfWork.Complete();
                return RedirectToAction("Edit", new { id = bloque.BloqueId });
            }
            return View(bloque);
        }

        // GET: /Bloques/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var bloque = _unitOfWork.Bloques.GetWithGrupos(id.Value);
            if (bloque == null)
            {
                return HttpNotFound();
            }
            ViewBag.json = new HtmlString(JsonConvert.SerializeObject(bloque.Grupos, new JsonSerializerSettings { ReferenceLoopHandling = ReferenceLoopHandling.Ignore }));
            return View(bloque);
        }

        // POST: /Bloques/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "BloqueId,Nombre,KilocaloriasTotales")] Bloque bloque)
        {
            if (ModelState.IsValid)
            {
                var _bloque = _unitOfWork.Bloques.Get(bloque.BloqueId);

                _bloque.Nombre = bloque.Nombre;
                _bloque.KilocaloriasTotales = bloque.KilocaloriasTotales;
                _unitOfWork.Complete();
                return RedirectToAction("Index");
            }
            return View(bloque);
        }

        // GET: /Bloques/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var bloque = _unitOfWork.Bloques.Get(id.Value);
            if (bloque == null)
            {
                return HttpNotFound();
            }
            return PartialView(bloque);
        }

        // POST: /Bloques/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            _unitOfWork.Bloques.Remove(id);
            _unitOfWork.Complete();
            return RedirectToAction("Index");
        }

        // GET: /Bloques/GrupoCreate
        public ActionResult GrupoCreate(int bloqueId)
        {
            ViewBag.BloqueId = bloqueId;
            ViewBag.GrupoAlimenticioId = new SelectList(_unitOfWork.GruposAlimenticios.GetAll(), "GrupoAlimenticioId", "Grupo");
            return PartialView("GrupoCreate");
        }

        // POST: /Bloques/GrupoCreate
        [HttpPost, ActionName("GrupoCreate")]
        [ValidateAntiForgeryToken]
        public ActionResult GrupoCreate([Bind(Include = "GrupoId,Nombre,Grupo,Porcentaje,Gramos,Kilocalorias,Equivalencias,BloqueId,GrupoAlimenticioId")] Grupo model)
        {
            if (ModelState.IsValid)
            {
                _unitOfWork.Grupos.Add(model);
                _unitOfWork.Bloques.Get(model.BloqueId).KilocaloriasTotales += model.Kilocalorias;
                _unitOfWork.Complete();
                return RedirectToAction("Edit", new { id = model.BloqueId });

            }
            return RedirectToAction("Edit", model.BloqueId);
        }

        // GET: /Bloques/GrupoEdit/1
        public ActionResult GrupoEdit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var grupo = _unitOfWork.Grupos.Get(id.Value);
            if (grupo == null)
            {
                return HttpNotFound();
            }
            ViewBag.GrupoAlimenticioId = new SelectList(_unitOfWork.GruposAlimenticios.GetAll(), "GrupoAlimenticioId", "Grupo", grupo.GrupoAlimenticio.GrupoAlimenticioId);
            return PartialView("GrupoEdit", grupo);
        }

        // POST: /Bloques/GrupoEdit/1
        [HttpPost, ActionName("GrupoEdit")]
        [ValidateAntiForgeryToken]
        public ActionResult GrupoEdit([Bind(Include = "Nombre,Grupo,Porcentaje,Gramos,Kilocalorias,Equivalencias,GrupoId,BloqueId,GrupoAlimenticioId")] Grupo model)
        {
            if (ModelState.IsValid)
            {
                var _grupo = _unitOfWork.Grupos.Get(model.GrupoId);
                _grupo.Nombre = model.Nombre;
                _grupo.Porcentaje = model.Porcentaje;
                _grupo.Gramos = model.Gramos;
                _grupo.Kilocalorias = model.Kilocalorias;
                _grupo.Equivalencias = model.Equivalencias;
                _grupo.BloqueId = model.BloqueId;
                _grupo.GrupoAlimenticioId = model.GrupoAlimenticioId;
                _unitOfWork.Bloques.CalculateKilocalorias(model.BloqueId);
                _unitOfWork.Complete();
                    return RedirectToAction("Edit", new { id = model.BloqueId });
                
            }
            return RedirectToAction("Edit", new { id = model.BloqueId });
        }

        // GET: /Bloques/GrupoDelete/1
        public ActionResult GrupoDelete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var grupo = _unitOfWork.Grupos.Get(id.Value);
            if (grupo == null)
            {
                return HttpNotFound();
            }
            return PartialView("GrupoDelete", grupo);
        }

        // POST: /Bloques/GrupoDelete/1
        [HttpPost, ActionName("GrupoDelete")]
        [ValidateAntiForgeryToken]
        public ActionResult GrupoDelete(int id, int bloqueId)
        {
            _unitOfWork.Grupos.Remove(id);
            _unitOfWork.Complete();
            _unitOfWork.Bloques.CalculateKilocalorias(bloqueId);
            _unitOfWork.Complete();
            return RedirectToAction("Edit", new { id = bloqueId });
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
            }
            base.Dispose(disposing);
        }
    }
}

Sirindar/Controllers/DeportesController.cs
using System.Net;
using System.Web;
using System.Web.Mvc;
using Newtonsoft.Json;
using Sirindar.Core;
using Sirindar.Core.UnitOfWork;
using Sirindar.Helpers;

namespace Sirindar.Controllers
{
    [Authorize(Roles = "Admin")]
    public class DeportesController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;

        public DeportesController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        public ActionResult Index()
        {
            var dd = new HtmlString(JsonConvert.SerializeObject(_unitOfWork.Deportes.GetAll(), new JsonSerializerSettings
            {
                ReferenceLoopHandling = ReferenceLoopHandling.Ignore
            }));
            ViewBag.json = new HtmlString(JsonConvert.SerializeObject(_unitOfWork.Deportes.GetAll(), new JsonSerializerSettings
            {
                ReferenceLoopHandling = ReferenceLoopHandling.Ignore
            }));
            return View();
        }
        
        public ActionResult Create()
        {
            ViewBag.clasificacionDeporteId = new SelectList(_unitOfWork.ClasificacionesDeportes.GetAll(), "ClasificacionDeporteId", "Descripcion");
            return View();
        }

        // POST: /Deportes/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "DeporteId,Nombre,TipoEnergia,Clasificacion,ClasificacionDeporteId")] Deporte deporte)
        {
            if (ModelState.IsValid)
            {
                _unitOfWork.Deportes.Add(deporte);
                _unitOfWork.Complete();
                return RedirectToAction("Index");
            }
            ViewBag.clasificacionDeporteId = new SelectList(_unitOfWork.ClasificacionesDeportes.GetAll(), "ClasificacionDeporteId", "Descripcion");
            return View(deporte);
        }

        // GET: /Deportes/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var deporte = _unitOfWork.Deportes.Get(id.Value);
            if (deporte == null)
            {
                return HttpNotFound();
            }

            ViewBag.TipoEnergia = new SelectList(SirindarControls.EnumAsList<Energia>(), "Value", "Text", (int)deporte.TipoEnergia);
            ViewBag.clasificacionDeporteId = new SelectList(_unitOfWork.ClasificacionesDeportes.GetAll(), "ClasificacionDeporteId", "Descripcion", deporte.Clasificacion.ClasificacionDeporteId);
            return View(deporte);
        }

        // POST: /Deportes/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "DeporteId,Nombre,TipoEnergia,ClasificacionDeporteId")] Deporte deporte)
        {
            if (ModelState.IsValid)
            {
                var _deporte = _unitOfWork.Deportes.Get(deporte.DeporteId);
                _deporte.Nombre = deporte.Nombre;
                _deporte.TipoEnergia = deporte.TipoEnergia;
                _deporte.ClasificacionDeporteId = deporte.ClasificacionDeporteId;
                _unitOfWork.Complete();
                return RedirectToAction("Index");
            }
            ViewBag.TipoEnergia = new SelectList(SirindarControls.EnumAsList<Energia>(), "Value", "Text", (int)deporte.TipoEnergia);
            ViewBag.clasificacionDeporteId = new SelectList(_unitOfWork.ClasificacionesDeportes.GetAll(), "ClasificacionDeporteId", "Descripcion", deporte.Clasificacion.ClasificacionDeporteId);
            return View(deporte);
        }

        // GET: /Deportes/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var deporte = _unitOfWork.Deportes.Get(id.Value);
            if (deporte == null)
            {
                return HttpNotFound();
            }
            return PartialView(deporte);
        }

        // POST: /Deportes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            _unitOfWork.Deportes.Remove(id);
            _unitOfWork.Complete();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
            }
            base.Dispose(disposing);
        }
    }
}

Sirindar/Controllers/HorariosController.cs
using System.Net;
using System.Web;
using System.Web.Mvc;
using Newtonsoft.Json;
using Sirindar.Core;
using Sirindar.Core.UnitOfWork;
using Sirindar.Helpers;

namespace Sirindar.Controllers
{
    [Authorize(Roles="Admin")]
    public class HorariosController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;

        public HorariosController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        // GET: /Horarios/
        public ActionResult Index()
        {
            ViewBag.json = new HtmlString(JsonConvert.SerializeObject(_unitOfWork.Horarios.GetAll(), new JsonSerializerSettings { ReferenceLoopHandling = ReferenceLoopHandling.Ignore }));
            return View();
        }

        // GET: /Horarios/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            var horario = _unitOfWork.Horarios.Get(id.Value);
            if (horario == null)
                return HttpNotFound();

            ViewBag.Nombre = new SelectList(SirindarControls.EnumAsList<ComidasDia>(), "Value", "Text", (int)horario.Nombre);
            return PartialView(horario);
        }

        // POST: /Horarios/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include="HorarioId,Inicia,Finaliza,FechaAlta,Nombre")] Horario model)
        {
            if (ModelState.IsValid)
            {
                var horario = _unitOfWork.Horarios.Get(model.HorarioId);
                horario.Inicia = model.Inicia;
                horario.Finaliza = model.Finaliza;
                horario.Nombre = model.Nombre;
                _unitOfWork.Complete();
                return RedirectToAction("Index");
            }
            ViewBag.Nombre = new SelectList(SirindarControls.EnumAsList<ComidasDia>(), "Value", "Text", model.HorarioId);
            return View(model);
        }       

      
    }
}

Sirindar/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Mi aplicación ASP.NET</title>
    <!-- Bootstrap Core CSS -->
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <!-- MetisMenu CSS -->
    <link href="~/Content/metisMenu.min.css" rel="stylesheet" />
    <!-- Timeline CSS -->
    <link href="~/Content/timeline.css" rel="stylesheet" />
    <!-- Custom CSS -->
    <link href="~/Content/sb-admin-2.css" rel="stylesheet" />
    <!-- Morris Charts CSS -->
    <link href="~/Content/morris.css" rel="stylesheet" />
    <!-- Custom Fonts -->
    <link href="~/Content/font-awesome.min.css" rel="stylesheet" />
    <!-- Custom Sirindar CSS -->
    <link href="~/Content/sirindar.css" rel="stylesheet" />
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body style="background-color: lightgray">
    <div class="col-md-1"></div>
    <div class="col-md-10">
        @*Modal que se muestra en toda la pagina*@
        <div class="modal fade" id="idModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                </div>
            </div>
        </div>
        <div id="wrapper" style="background-color: white">
            <!-- Navigation -->
            <nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0;border-bottom-width: thin;border-bottom-color: #0E2D62;">
                <div class="col-md-12" style="background-image: url('../../sHeaderSirindar.png'); background-repeat: round; background-size: contain;">
                    <img src="~/sHeaderSirindarTransparent.png" style="width: 100%; height: 100%;" />
                </div>
            </nav>
            <nav id="sirindar-navbar" class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0;border-bottom-width: thin;border-bottom-color: #091E5D;">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="@Url.Action("Index", "Home", null)">SIRINDAR</a>
                </div>
                <!-- /.navbar-header -->
                @Html.Partial("_LoginPartial")
                <!-- /.navbar-top-links -->
                @if (User.IsInRole("Admin"))
                {
                    <div class="navbar-default sidebar" role="navigation">
                        <div class="sidebar-nav navbar-collapse">
                            <ul class="sirindar-nav">
                                <li class="sirindar-header">
                                    <a class="sirindar-disable-pointer">UTILERIAS</a>
                                </li>
                                <li class="sirindar-subheader">
                                    <a class="sirindar-disable-pointer">CATALAGOS</a>
                                </li>
                                <li>
                                    <a href="@Url.Action("Index", "Account")"><i class="fa fa-users fa-fw"></i> Usuarios</a>
                                </li>
                                <li>
                                    <a href="@Url.Action("Index", "Deportes")"><i class="fa fa-dribbble fa-fw"></i> Deportes</a>
                                </li>
                                <li>
                                    <a href="@Url.Action("Index", "Bloques")"><i class="fa fa-tasks fa-fw"></i> Bloques</a>
                                </li>
                                <li>
                                    <a href="@Url.Action("Index","Horarios")"><i class="fa fa-clock-o fa-fw"></i> Horarios</a>
                                </li>
                                <li>
                                    <a href="@Url.Action("Index", "Deportistas")"><i class="fa fa-trophy fa-fw"></i> Deportistas</a>
                                </li>
                                <li class="sirindar-subheader">
                                    <a class="sirindar-disable-pointer">ASIGNACIONES</a>
                                </li>
                                <li>
                                    <a href="@Url.Action("Index", "AsignacionBloques")"><i class="fa fa-edit fa-fw"></i> Asignacion Bloques</a>
                                </li>
                                <li>
                                    <a href="@Url.Action("Index", "AsignacionHorarios")"><i class="fa fa-edit fa-fw"></i> Asignacion Comidas</a>
                                </li>
                            </ul>
                        </div>
                        <!-- /.sidebar-collapse -->
                    </div>
                }
                <!-- /.navbar-static-side -->
            </nav>
            <div id="page-wrapper">
                @RenderBody()
            </div>

            <!-- /#page-wrapper -->
        </div>



        @*@Scripts.Render("~/bundles/jquery")
            @Scripts.Render("~/bundles/bootstrap")*@
        <!-- /#wrapper -->
        <!-- jQuery -->
        <script src="~/Scripts/jquery.min.js"></script>
        <!-- Bootstrap Core JavaScript -->
        <script src="~/Scripts/bootstrap.min.js"></script>
        <!-- Metis Menu Plugin JavaScript -->
        <script src="~/Scripts/metisMenu.min.js"></script>
        <!-- Morris Charts JavaScript -->
        <script src="~/Scripts/raphael-min.js"></script>
        @*<script src="~/Scripts/morris.min.js"></script>
            <script src="~/Scripts/morris-data.js"></script>*@
        <!-- Custom Theme JavaScript -->
        <script src="~/Scripts/sb-admin-2.js"></script>
        @Scripts.Render("~/bundles/angularjs")
        @RenderSection("scripts", required: false)
        <script>
            $("#myCollapsible").on('show.bs.collapse', function () {
                alert(2);
            });
            $("#myCollapsible").on('hide.bs.collapse', function () {
                alert(2);
            });

            function ff() { $("#myCollapsible").collapse('toggle'); }

        </script>
    </div>
    <div class="col-md-1"></div>

</body>
</html>